import uuid
from datetime import datetime

from sqlalchemy import BigInteger, DateTime, ForeignKey, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.common.database import Base


class TelegramLink(Base):
    """Binds a Telegram chat to a Wealth-Lens user. Starts life as a pending
    one-time code (chat_id NULL) generated by the authenticated web app; the
    /link command completes it by setting chat_id and clearing the code."""

    __tablename__ = "telegram_links"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    chat_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True, unique=True)
    link_code: Mapped[str | None] = mapped_column(Text, nullable=True, unique=True)
    code_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
